### ISSUE TITLE
Adding types or publishing them separately for typescript support

### ISSUE THREAD

**Issue by jkvyff** [ignasdamunskis/passive-events-support#1]
Heya, sweet project! Added some quick typescript types that I had used. If you wanted to publish them along with you project, it could help people with a typescript codebase get going. Though fair enough if you just wanted a straight JS project.
```typescript
declare module 'passive-events-support/src/utils' {
    type Event =
        | 'touchstart'
        | 'touchmove'
        | 'touchcenter'
        | 'touchend'
        | 'touchleave'
        | 'wheel'
        | 'mousewheel'

    interface Listener {
        element: string;
        event: Event;
        prevented?: boolean;
    }

    export interface PassiveSupportOptions {
        debug?: boolean;
        events?: Event[];
        listeners?: Listener[];
    }
    export function passiveSupport(options?: PassiveSupportOptions): void;
}
```

**Comment by ignasdamunskis** [comment]
Hi @jkvyff, I would love to enable it for typescript, but unfortunately so far I have never worked with typescript.

**Comment by ignasdamunskis** [comment]
Thank you for the code. Added the suggested types: https://github.com/ignasdamunskis/passive-events-support/commit/0387e4850d0c24b97741f3f17720cdec80b51aac
